---
- name: Enable Splunkd SSL
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    section: sslConfig
    option: enableSplunkdSSL
    value: "{{ splunk.ssl.enable }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    mode: 0660
  when: "'enable' in splunk.ssl and splunk.ssl.enable"

- name: Set Splunkd CA
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    section: sslConfig
    option: sslRootCAPath
    value: "{{ splunk.ssl.ca }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    mode: 0660
  when: "'ca' in splunk.ssl and splunk.ssl.ca"

- name: Set Splunkd cert
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    section: sslConfig
    option: serverCert
    value: "{{ splunk.ssl.cert }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    mode: 0660
  when: "'cert' in splunk.ssl and splunk.ssl.cert"

- name: Set Splunkd SSL password
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    section: sslConfig
    option: sslPassword
    value: "{{ splunk.ssl.password }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    mode: 0660
  when: "'password' in splunk.ssl and splunk.ssl.password"
